# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 35263c765ac4b78462f0e4d8c8e130c3477eb47f3e992c7327fe25a6bdd11db9ee146a7ca8bd9cc4fc30f091528d484d4c3d5014a365a485d8a864e3f2ff0517

test:
  secret_key_base: 96d5180f67280c741e1dc12cc3ced6489efb444d732753a1d28de84b3eb55e4acee2687c5e969cee71cbc97af4bef8d6978f210b0ed01b1bd3928bfb8b519ff1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
